apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-app-monitor
  namespace: monitoring
  labels:
    release: prometheus
    app: test-app
spec:
  selector:
    matchLabels:
      app: test-app
  endpoints:
    - targetPort: 8080
      path: /metrics
      interval: 15s
      scheme: http
  namespaceSelector:
    matchNames:
      - default